// Business Rules Constants
export const CART_RULES = {
  MAX_ITEMS: 50,
  MAX_QUANTITY_PER_ITEM: 10,
  MIN_QUANTITY_PER_ITEM: 1,
  EXPIRATION_HOURS: 24,
  ABANDONED_CART_DAYS: 30,
} as const;

export const ORDER_RULES = {
  MIN_ORDER_VALUE: 1.00,
  MAX_ORDER_VALUE: 10000.00,
  MAX_ITEMS_PER_ORDER: 100,
  PROCESSING_TIME_HOURS: 24,
  SHIPPING_CUTOFF_HOUR: 14, // 2 PM
  RETURN_PERIOD_DAYS: 30,
} as const;

export const PRODUCT_RULES = {
  MIN_PRICE: 0.01,
  MAX_PRICE: 999999.99,
  MIN_NAME_LENGTH: 3,
  MAX_NAME_LENGTH: 100,
  MIN_DESCRIPTION_LENGTH: 10,
  MAX_DESCRIPTION_LENGTH: 5000,
  MAX_IMAGES: 10,
  MIN_IMAGES: 1,
} as const;

export const USER_RULES = {
  MIN_AGE: 13,
  MIN_NAME_LENGTH: 2,
  MAX_NAME_LENGTH: 50,
  MIN_PASSWORD_LENGTH: 8,
  MAX_LOGIN_ATTEMPTS: 5,
  SESSION_TIMEOUT_MINUTES: 480, // 8 hours
} as const;

export const INVENTORY_RULES = {
  DEFAULT_LOW_STOCK_THRESHOLD: 5,
  MIN_STOCK_LEVEL: 0,
  MAX_STOCK_LEVEL: 999999,
  AUTO_RESTOCK_QUANTITY: 10,
  OVERSTOCK_THRESHOLD: 1000,
} as const;

export const PRICING_RULES = {
  TAX_RATE_DEFAULT: 19.0, // Chilean VAT
  SHIPPING_COST_BASE: 5.00,
  SHIPPING_COST_PER_ITEM: 1.00,
  FREE_SHIPPING_THRESHOLD: 50.00,
  DISCOUNT_MAX_PERCENTAGE: 90,
} as const;

export const SEO_RULES = {
  MIN_SEO_SCORE: 0,
  MAX_SEO_SCORE: 100,
  EXCELLENT_SEO_THRESHOLD: 90,
  GOOD_SEO_THRESHOLD: 80,
  AVERAGE_SEO_THRESHOLD: 60,
  POOR_SEO_THRESHOLD: 30,
} as const;

export const REVIEW_RULES = {
  MIN_RATING: 1,
  MAX_RATING: 5,
  MIN_REVIEW_LENGTH: 10,
  MAX_REVIEW_LENGTH: 1000,
  MAX_REVIEWS_PER_PRODUCT: 1000,
  MIN_DAYS_BEFORE_REVIEW: 1,
  MAX_DAYS_AFTER_PURCHASE: 90,
  HELPFUL_VOTES_THRESHOLD: 5,
} as const;

export const NOTIFICATION_RULES = {
  MAX_NOTIFICATIONS_PER_DAY: 50,
  MAX_NOTIFICATIONS_PER_HOUR: 10,
  NOTIFICATION_EXPIRY_DAYS: 30,
  PRICE_DROP_THRESHOLD: 5.00, // Minimum price drop to notify
} as const;